### ISSUE TITLE
I am adding one event but 3 events are shown in  column

### ISSUE THREAD

**Issue by lakhwinderdebut** [thellmund/Android-Week-View#97] opened 2019-07-26 12:38 UTC
I dont know its a bug or a feature
 When the visible days are set to 1, then after adding a single event, it shows three

Please check the code for it

override fun onMonthChange(startDate: Calendar, endDate: Calendar): List<WeekViewDisplayable<Event>> {
        return getEvents()
    }

    private fun getEvents(): List<WeekViewDisplayable<Event>> {
        Log.e("getEvents","getEvents")
        val events = mutableListOf<WeekViewDisplayable<Event>>()

        val startTime = Calendar.getInstance()
        startTime.set(Calendar.HOUR_OF_DAY, 3)
        startTime.set(Calendar.MINUTE, 0)
        val endTime = startTime.clone() as Calendar
        endTime.add(Calendar.MINUTE, 50)

        val event  = createEvent(1,"MY EVENT ", startTime, endTime, R.color.colorAccent, isAllDay = false, isCanceled = false)

        events.add(event)

        return events
    }

check the screenshot

https://imge.to/i/d5Qz6

**Comment by thellmund** [comment] 2019-07-26 12:44
Duplicate of #8. Hope to improve this soon (see #87).

**Closed by thellmund** 2019-07-26 12:44 UTC

**Comment by lakhwinderdebut** [comment] 2019-07-29 04:04
How to set the event width?
 
I need to show three events at the same time  in a single day so I need them to  column for a single day

**Comment by thellmund** [comment] 2019-07-29 06:49
WeekView automatically puts events that take place at the same time into columns. For instance, if you have three events that start at 10 AM on the same date, each event will occupy a third of the width.
