### ISSUE TITLE
Custom event chip

### ISSUE THREAD

**Issue by 80avin** [thellmund/Android-Week-View#9] opened 2018-11-20 20:11 UTC
Can I create custom event chip ? Like in listview, I create the view which will be in list !

**Comment by SapuSeven** [comment] 2018-11-20 20:42
I believe there is currently no support for this.

The problem is that the WeekView has its own rendering code with its own drawing logic. It does not rely on Views (and therefore layouts) to display the events, so this would be quite a big challenge to implement.

**Comment by 80avin** [comment] 2018-11-20 21:36
Ok. I wish this comes up in future releases !
Further, is there any workaround ? If needed, I can tweak one or two source files.

**Comment by SapuSeven** [comment] 2018-11-20 21:41
If you really want to change the library source code, it should be possible by editing the `draw` function in `EventChip.java`.

**Comment by thellmund** [comment] 2019-07-21 11:48
Closing this issue, as new styling options were added in [version 3.4](https://github.com/thellmund/Android-Week-View/releases). If you want more styling options, open a new issue.

**Closed by thellmund** 2019-07-21 11:48 UTC
Labels: enhancement
