### ISSUE TITLE
 AsyncLoader attempted to cache 4 periods, which should not be possible.

### ISSUE THREAD

**Issue by thelittlefireman** [thellmund/Android-Week-View#109] opened 2019-09-02 18:13 UTC
**Describe the bug**
Lots of errors on crashlytics :  

```
Fatal Exception: java.lang.IllegalStateException: AsyncLoader attempted to cache 4 periods, which should not be possible.
       at com.alamkanak.weekview.AsyncLoader.updateEventsCache + 76(AsyncLoader.java:76)
       at com.alamkanak.weekview.AsyncLoader.submit + 61(AsyncLoader.java:61)
       at com.alamkanak.weekview.WeekView.submit + 1267(WeekView.java:1267)
       at com.esirteam.rennes1univtools.ui.mainactivity.fragment.edt.EDTFragment.updateWeekViewEvents + 234(EDTFragment.java:234)
       at com.esirteam.rennes1univtools.ui.mainactivity.fragment.edt.EDTFragment.lambda$onResume$4 + 216(EDTFragment.java:216)
       at com.esirteam.rennes1univtools.ui.mainactivity.fragment.edt.-$$Lambda$EDTFragment$eUgwFMjKm0cn_ON9zyTAplQ07YQ.onChanged + 4(-.java:4)
       at androidx.lifecycle.LiveData.considerNotify + 131(LiveData.java:131)
       at androidx.lifecycle.LiveData.dispatchingValue + 149(LiveData.java:149)
       at androidx.lifecycle.LiveData.setValue + 307(LiveData.java:307)
       at androidx.lifecycle.MutableLiveData.setValue + 50(MutableLiveData.java:50)
       at com.esirteam.rennes1univtools.ui.mainactivity.fragment.edt.EDTFragmentViewModel$1.onChanged + 143(EDTFragmentViewModel.java:143)
       at com.esirteam.rennes1univtools.ui.mainactivity.fragment.edt.EDTFragmentViewModel$1.onChanged + 139(EDTFragmentViewModel.java:139)
       at androidx.lifecycle.MediatorLiveData$Source.onChanged + 152(MediatorLiveData.java:152)
       at androidx.lifecycle.LiveData.considerNotify + 131(LiveData.java:131)
       at androidx.lifecycle.LiveData.dispatchingValue + 149(LiveData.java:149)
       at androidx.lifecycle.LiveData.setValue + 307(LiveData.java:307)
       at androidx.lifecycle.MutableLiveData.setValue + 50(MutableLiveData.java:50)
       at androidx.lifecycle.LiveData$1.run + 91(LiveData.java:91)
       at android.os.Handler.handleCallback + 808(Handler.java:808)
       at android.os.Handler.dispatchMessage + 101(Handler.java:101)
       at android.os.Looper.loop + 166(Looper.java:166)
       at android.app.ActivityThread.main + 7523(ActivityThread.java:7523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run + 245(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main + 921(ZygoteInit.java:921)
```

**To Reproduce**
i juste populate week view on livedata with
```
 mWeekView.submit(lessonList);
```

**Expected behavior**
I don't know how to deal with it

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Additional context**
 - Android version: [e.g. Android 9.0]
 - WeekView version: [e.g. 3.4.2]

**Comment by thellmund** [comment] 2019-09-02 18:25
Duplicate of #107. Also, you should probably not use the snapshot version in a production app.

**Closed by thellmund** 2019-09-02 18:25 UTC
Labels: bug
