### ISSUE TITLE
Date is one day off in newest update, if i give data for may 2nd it sets date for may 1st

### ISSUE THREAD

**Issue by jenish27** [thellmund/Android-Week-View#57] opened 2019-04-29 17:10 UTC

**Comment by thellmund** [comment] 2019-04-29 17:20
What do you mean by “give data for May 2nd”? Please provide a more detailed description of what is wrong.

**Comment by jenish27** [comment] 2019-04-29 17:42
So i have a meeting i create for may 2nd 1556823600000 and submit it, but the calendar creates it for may 1st

**Comment by jenish27** [comment] 2019-04-29 17:42
Also in onMonthChange it use to give startdate as 1st of the month period but now its gives start date as the last day of the previous month

**Comment by jenish27** [comment] 2019-04-29 17:47
![Screen Shot 2019-04-29 at 10 47 17 AM](https://user-images.githubusercontent.com/16213838/56915765-3170d080-6a6c-11e9-9c08-e3f6626c4d9d.png)

**Comment by jenish27** [comment] 2019-04-29 17:47
<img width="1067" alt="Screen Shot 2019-04-29 at 10 47 37 AM" src="https://user-images.githubusercontent.com/16213838/56915785-3cc3fc00-6a6c-11e9-8512-4a7e23eb51db.png">

**Comment by jenish27** [comment] 2019-04-29 17:48
as you can see the above I create a metting for may 2nd but it creates for may 1st

**Comment by thellmund** [comment] 2019-04-29 18:17
I can’t reproduce either of these issues.
- I just logged the dates with which `onMonthChange()` is called. Looks pretty normal to me: 
![Screen Shot 2019-04-29 at 20 13 22](https://user-images.githubusercontent.com/11819826/56917264-5c364580-6abb-11e9-8431-f975ea753935.png)
- Creating an event with the provided timestamp (`1556823600000`) creates an event on May 2nd, exactly as intended.

Please provide me with a [SSCCE](http://www.sscce.org) that demonstrates the issues.

**Comment by jenishStudent** [comment] 2019-04-29 18:26
https://github.com/jenishStudent/Android-Week-View/tree/master

**Comment by jenishStudent** [comment] 2019-04-29 18:26
here is the link

**Comment by jenishStudent** [comment] 2019-04-29 18:26
please show me a photo of your result

**Comment by jenishStudent** [comment] 2019-04-29 18:27
as you can see my forked is uptodate with your branch notifydatasetchanged one

**Comment by jenishStudent** [comment] 2019-04-29 18:31
Let me know once you run the above code i provided

**Comment by jenishStudent** [comment] 2019-04-29 18:31
Also is there better way to communicate?

**Comment by thellmund** [comment] 2019-04-29 19:00
What’s your time zone?

**Comment by jenishStudent** [comment] 2019-04-29 19:02
pst

**Comment by jenishStudent** [comment] 2019-04-29 19:09
drawEventsForDate breaking into this method i see its drawing for the current date May 2nd but its displaying for may1st

**Comment by jenishStudent** [comment] 2019-04-29 19:22
<img width="378" alt="Screen Shot 2019-04-29 at 12 21 43 PM" src="https://user-images.githubusercontent.com/42646380/56920942-646d9100-6a79-11e9-96d0-40fb2f8ae8f1.png">
  val dayLabel = config.dateTimeInterpreter.interpretDate(day.toCalendar())

**Comment by jenishStudent** [comment] 2019-04-29 19:22
theres your issue

**Comment by thellmund** [comment] 2019-04-29 19:26
It looks like there’s a time zone issue in the `toCalendar()` extension function. I didn’t notice it before, as it did not cause issues in my time zone. I’ll implement a fix and let you know when I pushed to `develop`.

**Comment by jenishStudent** [comment] 2019-04-29 19:26
Ok I am looking into it as well will upadte you as well

**Comment by thellmund** [comment] 2019-04-29 19:41
I’ve pushed a new commit to `develop`. Could you give it a go and let me know if it fixes your issue?

**Comment by jenishStudent** [comment] 2019-04-29 19:47
![Screen Shot 2019-04-29 at 12 47 00 PM](https://user-images.githubusercontent.com/42646380/56922404-f6c36400-6a7c-11e9-9d0f-4ee5cc654758.png)

**Comment by jenishStudent** [comment] 2019-04-29 19:47
creates for all days

**Comment by thellmund** [comment] 2019-04-29 19:56
That’s due to your changes in `FakeEventsDatabase` ([line 41](https://github.com/jenishStudent/Android-Week-View/blob/master/sample/src/main/java/com/alamkanak/weekview/sample/database/FakeEventsDatabase.java#L41)). Given that the bug is fixed, I’ll close this issue now.

**Closed by thellmund** 2019-04-29 19:56 UTC

**Comment by jenishStudent** [comment] 2019-04-29 20:05
> That’s due to your changes in `FakeEventsDatabase` ([line 41](https://github.com/jenishStudent/Android-Week-View/blob/master/sample/src/main/java/com/alamkanak/weekview/sample/database/FakeEventsDatabase.java#L41)). Given that the bug is fixed, I’ll close this issue now.

How do i fix this?
