### ISSUE TITLE
All day event chip doesn't fit real size

### ISSUE THREAD

**Issue by verzhbitski** [thellmund/Android-Week-View#118] opened 2019-10-22 11:05 UTC
Hello, I got a problem using this lib. Want to know if I am doing anything wrong.

When I have an All day event that start on one day (A) and end on the next day (B), event chip on end day (B) is not displayed correctly (just 1dp line in header). For the first day (A) everything works fine.

I can provide more information, if needed.

 - Android version: Android 10
 - WeekView version: 4.0.0

Thanks.

**Comment by thellmund** [comment] 2019-10-23 13:15
Can you provide screenshots and, ideally, a sample app where the behavior is visible?

**Comment by thellmund** [comment] 2019-10-24 21:20
Thanks. I’ll try to have a look on the weekend.

**Comment by thellmund** [comment] 2019-10-28 14:05
I did take a look and found out the cause of the issue, but didn’t have the time to implement a fix. I will do that within the next few days.

**Comment by thellmund** [comment] 2019-10-31 02:33
I pushed a fix to develop. Could you give it a try by switching to `implementation "com.github.thellmund.Android-Week-View:core:develop-SNAPSHOT"` and then let me know if it resolves your issue?

**Comment by verzhbitski** [comment] 2019-11-01 09:26
I have tried your fix and now everything is perfect. Thank you!

**Closed** 2019-11-01 11:16 UTC
Labels: bug
