### ISSUE TITLE
Exception when rotating device

### ISSUE THREAD

**Issue by MikibeMiki** [thellmund/Android-Week-View#76] opened 2019-06-24 12:03 UTC
When device is rotated sometimes it crashes with following log:

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter $this$toCalendar
at com.alamkanak.weekview.DateUtils.toCalendar(DateExtensions.kt)
at com.alamkanak.weekview.WeekView.onRestoreInstanceState(WeekView.java:118)
at android.view.View.dispatchRestoreInstanceState(View.java:15805)
at android.view.View.restoreHierarchyState(View.java:15783)
at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:494)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1486)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:714)
at android.app.Activity.performStart(Activity.java:6930)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4785)
at android.app.ActivityThread.-wrap20(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:156)
```

**Comment by thellmund** [comment] 2019-06-24 12:33
I believe this is a duplicate of #66. The fix will be released as part of the next version. Feel free to re-open if the issue persists.

**Closed by thellmund** 2019-06-24 12:33 UTC
