### ISSUE TITLE
Crash on XML loadup

### ISSUE THREAD

**Issue by Huakas** [thellmund/Android-Week-View#130] opened 2020-01-12 13:35 UTC
My app crashes everytime with version 4.1 whereas in 4.0.1 no crashes occur. I don't have any code inside my Activity, except the auto-created onCreate and I created a basic WeekView according to the example here on GitHub. This is just a test app with nothing else except the WeekView in the layout XML.

The Error is (summarized):
InflateException in Binary XML File: Error inflating class com.alamkanak.weekview.WeekView
Caused by: java.lang.IllegalStateException: EmojiCompat is not initialized. Please call EmojiCompat.init() first
at com.alamkanak.weekview.AllDayEventsUpdater.<init>(AllDayEventsUpdater.kt:22)

If you need more infos, please ask me :)

**Comment by thellmund** [comment] 2020-01-13 16:59
Hi @Huakas, thanks for reporting this! I have just pushed a new version that fixes the issue for now. Let me know if everything works for you now.

**Comment by Huakas** [comment] 2020-01-13 19:15
Yeah, it is created at least.

There actually are two more errors. The first one is that there is no now line anymore and the second one is a bit dificult to explain. It behaves a little bit weird regarding "firstDayOfWeek". At some cases it doesnt show the right week with the current date, but instead jumps a week ahead.

Shall I open a new issue for them?

**Comment by thellmund** [comment] 2020-01-13 19:21
The now line is displayed correctly for me when I try the latest commit on `develop`. 
Can you provide me with a small sample app regarding the second issue?

**Comment by Huakas** [comment] 2020-01-13 20:31
How can I see which branch I use with gradle? 

Also I am using an empty Activity for this testing without any code in the java file. And the xml contains only this WeekView (and of course the parent LinearLayout):

<com.alamkanak.weekview.WeekView
  android:id="@id/weekView"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  app:adaptiveEventTextSize="true"
  app:allDayEventTextSize="12sp"
  app:columnGap="2dp"
  app:eventCornerRadius="5dp"
  app:eventTextColor="#ffffff"
  app:eventTextSize="12sp"
  app:showHeaderRowBottomLine="true"
  app:dayBackgroundColor="#05000000"
  app:firstDayOfWeek="monday"
  app:headerRowBackgroundColor="#ffefefef"
  app:headerRowPadding="12sp"
  app:horizontalScrollingEnabled="false"
  app:hourHeight="50dp"
  app:numberOfVisibleDays="7"
  app:showCurrentTimeFirst="false"
  app:showFirstDayOfWeekFirst="true"
  app:showHourSeparator="true"
  app:showNowLine="true"
  app:timeColumnTextColor="#8f000000"
  app:todayBackgroundColor="#1848adff"/>

The second error occurs for me whenever I set the smartphone date to sunday for example, but there are other cases, too. I saw this error yesterday, so you could try setting the system date to the 12th of Janurary.
I also tested this xml on two different android versions, android api level 29 and android api level 26 and on both versions there was no now line. Did I mess something up in the xml?

**Comment by Huakas** [comment] 2020-01-13 20:39
And while were at it, another error I encountered is that it is not possible to change the TimeColumn background color with setTimeColumnBackgroundColor(); whereas setHeaderRowBackgroundColor(); works fine.

I hope I'm not overwhelming you :D

**Comment by thellmund** [comment] 2020-01-13 20:54
Not at all – thanks for reporting all this! I have found the cause for the time column and now line issues, and have pushed a fix to `develop`. I will take a look at the issue surrounding dates in the next few days and will let you know once I have fixed them.

**Comment by Huakas** [comment] 2020-01-13 21:45
Nice, thanks a lot.
I look forward to hearing from you.

**Comment by thellmund** [comment] 2020-01-19 18:00
I just published version 4.1.2 with both fixes. Let me know if you discover anything else or have any other improvement suggestions 🙂

**Closed by thellmund** 2020-01-19 18:01 UTC
