### ISSUE TITLE
how to snap 7 days

### ISSUE THREAD

**Issue by MohammadB72** [thellmund/Android-Week-View#75] opened 2019-06-24 06:52 UTC
**hello :)
how can i snap 7 days**

**after scrolling weekView to right or left, snap to the next week or previous week?**

![Screenshot_20190624-112129](https://user-images.githubusercontent.com/15035925/59997405-420b8480-9672-11e9-9699-810cba7b474a.png)

**Comment by thellmund** [comment] 2019-07-17 10:55
Snappy scrolling is not implemented yet, but I want to address this soon. I’ll close this particular issue, as it’s a duplicate of #4.

**Closed** 2019-07-17 10:55 UTC
